lbj:
  db1:
    url: jdbc:mysql://localhost:3306/hm_planet?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  db2:
    enabled: true
    url: jdbc:mysql://localhost:3306/hm_planet_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  db3:
    enabled: true
    url: jdbc:mysql://localhost:3306/hm_planet?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456